name: Build ios App

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3' 

      - name: Install dependencies
        run: bundle install

      - name: Install CocoaPods
        run: pod install
        working-directory: ios

      - name: Set up Signing Certificate
        run: |
          echo "${{ secrets.SIGNING_CERTIFICATE }}" | base64 --decode > cert.p12
          security create-keychain -p "password" build.keychain
          security import cert.p12 -t agg -k ~/Library/Keychains/build.keychain -P "password" -A
          security list-keychains -d user -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "password" ~/Library/Keychains/build.keychain
          security set-keychain-settings -t 3600 -u ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "password" ~/Library/Keychains/build.keychain
        env:
          SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}

      - name: Build and Archive
        run: |
          xcodebuild -workspace ios/AwesomeProject.xcworkspace \
          -scheme AwesomeProject \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/AwesomeProject.xcarchive \
          clean archive \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }} \
          PROVISIONING_PROFILE_SPECIFIER=""

      - name: Export Archive
        run: |
          xcodebuild -exportArchive \
          -archivePath $PWD/build/AwesomeProject.xcarchive \
          -exportOptionsPlist ios/ExportOptions.plist \
          -exportPath $PWD/build \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }} \
          PROVISIONING_PROFILE_SPECIFIER=""
