name: Build iOS App

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install dependencies
      run: yarn install

    - name: Install Pods
      run: |
        cd ios
        pod install

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Increment build number
      run: |
        cd ios
        agvtool new-version -all $(($(agvtool what-version -terse) + 1))

    - name: Build iOS (Release)
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: ios/AwesomeProject.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          workspace-path: ios/AwesomeProject.xcworkspace
          output-path: "AwesomeProject.ipa"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: "AwesomeProject.ipa"
          path: "AwesomeProject.ipa"