name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Increment build number
        run: |
          cd ios
          agvtool new-version -all $(($(agvtool what-version -terse) + 1))


       - name: Set up Signing Certificate
          run: |
            echo "${{ secrets.SIGNING_CERTIFICATE }}" | base64 --decode > cert.p12
            security create-keychain -p "password" build.keychain
            security import cert.p12 -t agg -k ~/Library/Keychains/build.keychain -P "password" -A
            security list-keychains -d user -s ~/Library/Keychains/build.keychain
            security unlock-keychain -p "password" ~/Library/Keychains/build.keychain
            security set-keychain-settings -t 3600 -u ~/Library/Keychains/build.keychain
            security set-key-partition-list -S apple-tool:,apple: -s -k "password" ~/Library/Keychains/build.keychain
          env:
            SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}

      - name: Build iOS App
        env:
          XCODE_WORKSPACE: ios/AwesomeProject.xcworkspace
          XCODE_SCHEME: AwesomeProject
          CONFIGURATION: Release
        run: |
          xcodebuild \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration $CONFIGURATION \
            -sdk iphoneos \
            -archivePath $PWD/build/$XCODE_SCHEME.xcarchive \
            clean archive \
              DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            -allowProvisioningUpdates

      - name: Export iOS App
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/AwesomeProject.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $PWD/build/AwesomeProject

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: iOS App Build
          path: build/AwesomeProject/*.ipa
